[build]
  command = "cd backend && pnpm i"
  publish = "backend/src"

[build.environment]
  NODE_VERSION = "18"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/index"
  status = 200
